interface TableAllowancesEntry {
  lengthMin: number; // Lmin
  lengthMax: number; // Lmax
  diameterMin: number; // Dmin
  diameterMax: number; // Dmax
  Qnom: number; // Nominalny naddatek
  IT: number; // Klasa dokładności
  RA: number; // Chropowatość
  F: number; // Zalecany posuw
}

// Tabela 1.a
export const tableKlzgr: TableAllowancesEntry[] = [
  {
    lengthMin: 10,
    lengthMax: 16,
    diameterMin: 2,
    diameterMax: 5.4,
    Qnom: 1.6,
    IT: 14,
    RA: 5,
    F: 0.04,
  },
  {
    lengthMin: 10,
    lengthMax: 16,
    diameterMin: 4,
    diameterMax: 6.3,
    Qnom: 1.6,
    IT: 13,
    RA: 5,
    F: 0.1,
  },
];

// Tabela 1.b
export const tablekKlkszt: TableAllowancesEntry[] = [
  {
    lengthMin: 2.5,
    lengthMax: 4.0,
    diameterMin: 4.0,
    diameterMax: 6.3,
    Qnom: 0.4,
    IT: 12,
    RA: 5,
    F: 0.05,
  },
  {
    lengthMin: 2.5,
    lengthMax: 4.0,
    diameterMin: 6.3,
    diameterMax: 10.0,
    Qnom: 0.4,
    IT: 12,
    RA: 5,
    F: 0.1,
  },
];

// Tabela 1.c
export const tableKlwyk: TableAllowancesEntry[] = [
  {
    lengthMin: 2.5,
    lengthMax: 4.0,
    diameterMin: 4.0,
    diameterMax: 6.3,
    Qnom: 0.21,
    IT: 10,
    RA: 1.25,
    F: 0.032,
  },
  {
    lengthMin: 2.5,
    lengthMax: 4.0,
    diameterMin: 6.3,
    diameterMax: 10.0,
    Qnom: 0.24,
    IT: 9,
    RA: 1.25,
    F: 0.05,
  },
];

export function findAllowancesEntry(
  table: TableAllowancesEntry[],
  length: number,
  diameter: number
): TableAllowancesEntry | null {
  return (
    table.find(
      (entry) =>
        length >= entry.lengthMin &&
        length <= entry.lengthMax &&
        diameter >= entry.diameterMin &&
        diameter <= entry.diameterMax
    ) || null
  );
}

export function findAllowancesEntryZgr(
  diameter: number,
  length: number
): number | null {
  return findAllowancesEntry(tableKlzgr, length, diameter)?.Qnom || null;
}

export function findAllowancesEntryKlkszt(
  diameter: number,
  length: number
): number | null {
  return findAllowancesEntry(tablekKlkszt, length, diameter)?.Qnom || null;
}

export function findAllowancesEntryKlwyk(
  diameter: number,
  length: number
): number | null {
  return findAllowancesEntry(tableKlwyk, length, diameter)?.Qnom || null;
}

interface DeviationEntry {
  diameterMin: number; // Minimalna średnica nominalna
  diameterMax: number; // Maksymalna średnica nominalna
  deviations: { [accuracy: string]: number }; // Odchyłki dla każdej klasy dokładności
}

// Tabela 2.a
const tableDeviation: DeviationEntry[] = [
  {
    diameterMin: 8,
    diameterMax: 15,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 16,
    diameterMax: 25,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 26,
    diameterMax: 35,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 36,
    diameterMax: 50,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 51,
    diameterMax: 75,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 76,
    diameterMax: 100,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 105,
    diameterMax: 150,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 155,
    diameterMax: 200,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
  {
    diameterMin: 200,
    diameterMax: 250,
    deviations: { '1': 0.4, '2': 0.3, '3': 0.2 },
  },
];

export function findDeviation(
  diameter: number,
  accuracy: string
): number | null {
  // Znalezienie odpowiedniego wpisu w tabeli na podstawie średnicy
  const entry = tableDeviation.find(
    (item) => diameter >= item.diameterMin && diameter <= item.diameterMax
  );

  // Jeśli znaleziono wpis, zwróć odchyłkę dla podanej klasy dokładności
  if (entry && accuracy in entry.deviations) {
    return entry.deviations[accuracy];
  }

  // Jeśli nie znaleziono odpowiedniej odchyłki, zwróć null
  return null;
}

export function findClosestGreaterDiameter(diameter: number): number | null {
  const entry = tableDeviation.find(
    (item) => diameter >= item.diameterMin && diameter <= item.diameterMax
  );

  if (entry) {
    return entry.diameterMax;
  }

  return null;
}

interface ShaftToleranceEntry {
  diameterMin: number; // Minimalna średnica nominalna wału
  diameterMax: number; // Maksymalna średnica nominalna wału
  tolerances: {
    [toleranceClass: string]: {
      upperDeviation: number;
      lowerDeviation: number;
    };
  }; // Odchyłki górne i dolne dla każdej klasy tolerancji
}

// Tabela 3
const shaftToleranceTable: ShaftToleranceEntry[] = [
  {
    diameterMin: 0,
    diameterMax: 3,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 3,
    diameterMax: 6,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 6,
    diameterMax: 10,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 10,
    diameterMax: 18,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 18,
    diameterMax: 30,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 30,
    diameterMax: 50,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 50,
    diameterMax: 65,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 65,
    diameterMax: 80,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 80,
    diameterMax: 100,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 100,
    diameterMax: 120,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 120,
    diameterMax: 140,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 140,
    diameterMax: 160,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 160,
    diameterMax: 180,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 180,
    diameterMax: 200,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 200,
    diameterMax: 225,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 225,
    diameterMax: 250,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 250,
    diameterMax: 280,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 280,
    diameterMax: 315,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 315,
    diameterMax: 355,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 355,
    diameterMax: 400,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 400,
    diameterMax: 450,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
  {
    diameterMin: 450,
    diameterMax: 500,
    tolerances: {
      g5: { upperDeviation: 0, lowerDeviation: -6 },
      h5: { upperDeviation: -2, lowerDeviation: -8 },
      j5: { upperDeviation: -4, lowerDeviation: -10 },
      k5: { upperDeviation: -6, lowerDeviation: -12 },
      m5: { upperDeviation: -8, lowerDeviation: -14 },
      n5: { upperDeviation: -10, lowerDeviation: -16 },
      r5: { upperDeviation: -12, lowerDeviation: -18 },
      s5: { upperDeviation: -14, lowerDeviation: -20 },
      f6: { upperDeviation: -16, lowerDeviation: -22 },
      g6: { upperDeviation: -18, lowerDeviation: -24 },
      h6: { upperDeviation: -20, lowerDeviation: -26 },
      j6: { upperDeviation: -22, lowerDeviation: -28 },
      k6: { upperDeviation: -24, lowerDeviation: -30 },
      m6: { upperDeviation: -26, lowerDeviation: -32 },
      n6: { upperDeviation: -28, lowerDeviation: -34 },
      p6: { upperDeviation: -30, lowerDeviation: -36 },
      r6: { upperDeviation: -32, lowerDeviation: -38 },
      f7: { upperDeviation: -34, lowerDeviation: -40 },
      h7: { upperDeviation: -36, lowerDeviation: -42 },
      s7: { upperDeviation: -38, lowerDeviation: -44 },
      e8: { upperDeviation: -40, lowerDeviation: -46 },
      h8: { upperDeviation: -42, lowerDeviation: -48 },
      d9: { upperDeviation: -44, lowerDeviation: -50 },
      f9: { upperDeviation: -46, lowerDeviation: -52 },
      h9: { upperDeviation: -48, lowerDeviation: -54 },
      h11: { upperDeviation: -50, lowerDeviation: -56 },
      h12: { upperDeviation: -52, lowerDeviation: -58 },
    },
  },
];

export function findShaftTolerance(
  diameter: number,
  toleranceClass: string
): { upperDeviation: number; lowerDeviation: number } | null {
  // Znalezienie odpowiedniego wpisu w tabeli na podstawie średnicy
  const entry = shaftToleranceTable.find(
    (item) => diameter >= item.diameterMin && diameter <= item.diameterMax
  );

  // Jeśli znaleziono wpis, zwróć odchyłki dla podanej klasy tolerancji
  if (entry && toleranceClass in entry.tolerances) {
    return entry.tolerances[toleranceClass];
  }

  // Jeśli nie znaleziono odpowiednich odchyłek, zwróć null
  return null;
}
